# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import EchoService_pb2 as EchoService__pb2


class EchoerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/Echoer/SayHello',
                request_serializer=EchoService__pb2.EchoRequest.SerializeToString,
                response_deserializer=EchoService__pb2.EchoReply.FromString,
                )
        self.SayHelloAgain = channel.unary_unary(
                '/Echoer/SayHelloAgain',
                request_serializer=EchoService__pb2.EchoRequest.SerializeToString,
                response_deserializer=EchoService__pb2.EchoReply.FromString,
                )


class EchoerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHelloAgain(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EchoerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=EchoService__pb2.EchoRequest.FromString,
                    response_serializer=EchoService__pb2.EchoReply.SerializeToString,
            ),
            'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHelloAgain,
                    request_deserializer=EchoService__pb2.EchoRequest.FromString,
                    response_serializer=EchoService__pb2.EchoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Echoer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Echoer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Echoer/SayHello',
            EchoService__pb2.EchoRequest.SerializeToString,
            EchoService__pb2.EchoReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHelloAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Echoer/SayHelloAgain',
            EchoService__pb2.EchoRequest.SerializeToString,
            EchoService__pb2.EchoReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
